#!/bin/sh -eu

. $(dirname $0)/../core/setup.sh

banner Check small valid view
#---------------------

ROOT="$(pwd)/warden-cli-test-check"
mkdir -p ${ROOT}
trap "rm -rf ${ROOT}" EXIT

(
  set -eux
  cd $ROOT
  VIEW=$(../${WARDEN_GEN} gen -s 2 -c 1000)
  ../${WARDEN} check  "${VIEW}"
)
