#!/bin/sh -eu

. $(dirname $0)/../core/setup.sh

banner Check small valid view
#---------------------

ROOT="$(pwd)/warden-cli-test-check"
mkdir -p ${ROOT}
trap "rm -rf ${ROOT}" EXIT

(
  set -eux
  cd $ROOT
  VIEW=$(../${WARDEN_GEN} gen -d 14142 -s 1 -c 10000)
  # Restrict heap usage in order to fail if there's a memory-usage regression.
  ../${WARDEN} +RTS -M64M -RTS check  "${VIEW}"
  ../${WARDEN} +RTS -M64M -RTS sanity -f "${VIEW}"
)
