#!/bin/sh -eu

. $(dirname $0)/../core/setup.sh

banner Display Version
#---------------------

$WARDEN -v | grep -q warden

$WARDEN --version

banner Display Help
#------------------

$WARDEN -h

$WARDEN --help

WARDEN="$WARDEN --dry-run"

$WARDEN check .

$WARDEN check /not/a/real/view

$WARDEN check --file-format rfc4180 -e -v -r 300 -b 1000 -s ',' --text-freeform-threshold 9999 /not/a/real/view

$WARDEN check -s '\t' /not/a/real/view

$WARDEN check -s '	' /not/a/real/view

$WARDEN check-file --file-format rfc4180 -e -r 300 -f -v -b 1000 -s , /not/a/real/view/year=2016/month=03/day=04/not/a/real/file --schema not-a-real-schema.json

$WARDEN infer /not/a/real/marker/file1 /not/a/real/marker/file2

$WARDEN infer -i -o foo.json -v -m 0.999 /not/a/real/marker/file1 /not/a/real/marker/file2

$WARDEN sanity /not/a/real/view

$WARDEN sanity -e -v /not/a/real/view
