#!/bin/sh -eu

. $(dirname $0)/../core/setup.sh

banner Display Version
#---------------------

$WARDEN -v | grep -q warden

$WARDEN --version

banner Display Help
#------------------

$WARDEN -h

$WARDEN --help

WARDEN="$WARDEN --dry-run"

$WARDEN check .

$WARDEN check /not/a/real/view

$WARDEN check -v -b 1000 -s ',' /not/a/real/view

$WARDEN check-file -f -v -b 1000 -s , /not/a/real/view/year=2016/month=03/day=04/not/a/real/file --schema not-a-real-schema.json

$WARDEN infer /not/a/real/marker/file1 /not/a/real/marker/file2
